### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RABot#1]
Things to implement on RABot:

- [ ] a poll system (needs to be better than the SimplePoll bot)
- [ ] mastery news (like Cel's bot)
- [ ] whatgame  (like Cel's bot)
- [ ] instant-unlocks warnings (like Cel's bot)
- [ ] `aotw` command: show link to the current Achievement of the Week

**Comment by vzapo** [comment]
Hi @meleu 
Is this roadmap still in use? Should all the above be still implemented or is there something new beside this?  Currently I've added `!timenow` command which would do something like `!timezone` command in PR #38 

I'd like to help more with the bot development and maintaining if that's ok and if there is anything else needed I'm up for it if I can help.

**Comment by meleu** [comment]
yo! that's great!
@vzapo what's your name on our discord server?
